FROM golang:1.23

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Установка wait-for-it
RUN apt-get update && apt-get install -y wait-for-it

CMD ["/bin/bash", "-c", "wait-for-it db:5432 -t 30 -- echo 'Database is ready' && TEST_DB_HOST=db go test ./... -v"] 