type Post {
  id: ID!
  title: String!
  content: String!
  comments: Boolean!
}

type Query {
  posts: [Post!]!
  comments(postID: ID!, limit: Int!, offset: Int!): [Comment!]!
  debugComments: [Comment!]! @deprecated(reason: "Только для отладки in-memory хранилища")
  commentTree(postID: ID!, commentID: ID!): Comment!
}

type Comment { 
  id: ID!
  text: String!
  postID: ID!
  parentCommID: ID
  replies(limit: Int, offset: Int): [Comment!]! @goField(forceResolver: true)
}

type Mutation { #методы
  createPost(title: String!, content: String!, comments: Boolean!): Post!
  createComment(text: String!, postID: ID!, parentCommID: ID): Comment!
}

type Subscription {
  newComment(postID: ID!): Comment!
}