package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"fmt"

	"github.com/headliner38/graphql-forum/graph/model"
)

// Replies is the resolver for the replies field.
func (r *commentResolver) Replies(ctx context.Context, obj *model.Comment) ([]*model.Comment, error) { //need
	return r.LoadRepliesForComment(obj), nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, title string, content string, comments bool) (*model.Post, error) { //need
	newPost := &model.Post{
		ID:       fmt.Sprintf("%d", len(r.Posts)+1),
		Title:    title,
		Content:  content,
		Comments: comments,
	}
	r.Posts = append(r.Posts, newPost)
	return newPost, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, text string, postID string, parentCommID *string) (*model.Comment, error) { //need
	if len(text) > 2000 { // ограничение по длине комментария
		return nil, fmt.Errorf("вы пытаетесь оставить комментарий длиной больше 2000 символов")
	}
	post, err := r.findPostByID(postID) // поиск по id для поста к которому хотим оставить комментарий
	if err != nil {
		return nil, err
	}
	if !post.Comments { // post.Comments = true, если можно оставлять комментарии.
		return nil, fmt.Errorf("автор отключил возможность оставлять комментарии к посту %v", post)
	}
	if parentCommID != nil {
		parentCommExists := false
		for _, comment := range r.Comments {
			if comment.ID == *parentCommID {
				if comment.PostID != postID {
					return nil, fmt.Errorf("основной комментарий не принадлежит данному посту")
				}
				parentCommExists = true
				break
			}
		}
		if !parentCommExists {
			return nil, fmt.Errorf("основного комментария с id: %v не существует", *parentCommID)
		}
	}

	newComment := &model.Comment{
		ID:           fmt.Sprintf("%d", len(r.Comments)+1),
		Text:         text,
		PostID:       postID,
		ParentCommID: parentCommID,
	}
	r.Comments = append(r.Comments, newComment)
	r.DebugCheckReplies() //new
	return newComment, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) { //need
	return r.Resolver.Posts, nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, postID string, limit int32, offset int32) ([]*model.Comment, error) { //need
	var result []*model.Comment

	for _, comment := range r.Resolver.Comments { // только основные комментарии
		if comment.PostID == postID && comment.ParentCommID == nil {
			result = append(result, comment)
		}
	}
	// Реализация пагинации
	if int(offset) >= len(result) {
		return []*model.Comment{}, nil // пустой для соответсвия типу
	}
	all := int(offset) + int(limit)
	if all > len(result) {
		all = len(result)
	}
	return result[offset:all], nil
}

// DebugComments is the resolver for the debugComments field.
func (r *queryResolver) DebugComments(ctx context.Context) ([]*model.Comment, error) { //tmp
	// временно, не забыть удалить.
	return r.Resolver.Comments, nil
}

// NewComment is the resolver for the newComment field.
func (r *subscriptionResolver) NewComment(ctx context.Context, postID string) (<-chan *model.Comment, error) { //need
	panic(fmt.Errorf("not implemented: NewComment - newComment"))
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
