// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID           string     `json:"id"`
	Text         string     `json:"text"`
	PostID       string     `json:"postID"`
	ParentCommID *string    `json:"parentCommID,omitempty"`
	Replies      []*Comment `json:"replies"`
}

type Mutation struct {
}

type Post struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Content  string `json:"content"`
	Comments bool   `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}
